#!/bin/bash
# Webup v1.05
#
# Install: the balise on site following this example: <!--82E5E592D805E37283A939D5B26D4917-->
# Param: sum = perform the checksum + lines counting, nosum = perform the checksum only
#

tmpfld='/var/tmp/webup/' ; mkdir -p "$tmpfld"
file_storreddate="${tmpfld}dateflag" ; [ ! -f "$file_storreddate" ] && echo "void" >"$file_storreddate"
file_curl="${tmpfld}curl"
file_curl_err="${file_curl}_err"
file_sum="${tmpfld}sum-"

log='/var/log/webup' ; touch "$log"
recipient='admin@nova.asity.fr'

log () {
	#$1 message
	echo "$1"
	echo "$(date '+%y-%m-%d %H:%M:%S') $1" >>"$log"
}

sites=(
 	"PILOTAGEGIRONDE.COM;		http://www.pilotagegironde.com;		615D292A0483C9F6FA3C71B7F3C162D6;		sum"
 	"ASITY-INTL.COM;			https://asity-intl.com;				71C29B281A8B6FA4FAEA0C505D49D2A3;		nosum"
 	"KLEENUP.ME;				https://www.kleenup.me;				9F73F738273C61D2D15083A19D2D290C;		sum"
# 	"ES.KLEENUP.ME;				http://es.kleenup.me;				EA9AE727F492A8B515C3F93C93B9E48C;		sum"
 	"JEFFTOP.COM;				https://jefftop.com;				82E5E592D805E37283A939D5B26D4917;		sum"
 	"VIAMETRIS.INFO;			http://viametris.info/iMMS/EN/;		C7F8D36866A38A3BB6526285C84C2768;		sum"
	"AZURLIGHT-SYS.COM;			http://azurlight-systems.com;		CB129AB6E7C4A785A058734B242CD8A6;		nosum"
)


cpt=0; pb=0
for ((i=0; i<${#sites[*]}; i++)); do
			#echo ">$i: ${sites[$i]}"
	data=($(echo ${sites[$i]} | sed -e 's/;[ ]*/;/g' -e 's/ /_/g' -e 's/;/ /g'))
	name=${data[0]}
	site=${data[1]}
	string=${data[2]}
	checksum=${data[3]}
	log "$name : $site : $string : $checksum"

	rm -f "$file_curl_err"
	curl -s $site >"$file_curl" 2>"$file_curl_err"
	
	if [ -f "$file_curl_err" ] && [ $(cat "$file_curl_err" | wc -l) -gt 0 ]; then
		log "curl error encountered"
		cat "$file_curl_err" | mail -s "Webup: ### SITE WEB $name: CURL ERROR ENCOUNTERED ###" $recipient
	fi
	
	if [ "$checksum" == "sum" ]; then
	
		currentsum=$(cat "$file_curl" | shasum -a 512)

		sitesum=${file_sum}$( echo $site | sed 's/\//_/g' )
		if [ ! -f "$sitesum" ]; then
			echo "$currentsum" >"$sitesum" 
		fi
		storeedsum=$(cat "$sitesum")
	
		if [ "$currentsum" != "$storeedsum" ]; then
			log "checksum changed"
			cat "$file_curl" | mail -s "Webup: ### SITE WEB $name: CHECKSUM CHANGED ###" $recipient
			let pb=pb+1	
		fi
	
	fi
	
	if ! [ "$(cat "$file_curl" | grep "<!--$string-->")" ]; then
		log "signup not found"
		cat "$file_curl" | mail -s "Webup: ### SITE WEB $name: SIGNUP NOT FOUND ###" $recipient
		let pb=pb+1	
	fi
	
	let cpt=cpt+1
done

if (( $pb == 0 )); then

	log "no problem detected"

	storeddate=$(cat "$file_storreddate")
	if [ "$storeddate" == "" ]; then
		storeddate=$(date '+%y%m%d')
		echo $storeddate >"$file_storreddate"
	fi

	currentdate=$(date '+%y%m%d')
	if [ "$currentdate" != "$storeddate" ]; then
		echo "-" | mail -s "Webup: no problem detected" $recipient
		echo $currentdate >"$file_storreddate" 
	fi
	
fi

